version: '3.8'

services:
  myapp:
    image: "${TESTING_IMAGE}"
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      myapp:
        condition: service_started
    command: curl --fail http://myapp:8888 || exit 1